version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: logs_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  logger:
    build:
      context: ./logger-service
    container_name: logger-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: logs_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "8081:8081"
  gateway:
    build:
      context: ./gateway-service
    container_name: gateway-service
    environment:
      LOGGER_SERVICE_URL: http://logger:8081
    depends_on:
      - logger
    ports:
      - "8088:8080"
volumes:
  postgres_data:
