# k8s-04-db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-db # Internal DNS name: 'postgres-db'
spec:
  selector:
    app: postgres-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP # Internal only service